### ISSUE TITLE
How to  update the stage of a deal?

### ISSUE THREAD

**Issue by techguydev** [IsraelOrtuno/pipedrive#92]
Hi, 

I would like to update the stage of a deal.

Not clear how to do it according with the docs.

Thanks

**Comment by IsraelOrtuno** [comment]
Every endpint has a mapped field, but since we use inheritance for this, it's quite tricky to be documenting all endpoints.

https://developers.pipedrive.com/docs/api/v1/#!/Deals/put_deals_id

This endpoint accepts a stage_id, so this should work:

```php
$pipedrive->deals->update($dealId, ['stage_id' => $stageId]);
```

Deals extends Resource:
https://github.com/IsraelOrtuno/pipedrive/blob/master/src/Resources/Basics/Resource.php#L85-L90
